# Generated by Django 6.0 on 2026-01-03 01:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(max_length=50)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit (Customer Account)'), ('ECASH', 'E-Cash (Paystack)'), ('MIXED', 'Mixed Payment')], default='CASH', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('VOIDED', 'Voided'), ('HELD', 'Held')], default='PENDING', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('discount_reason', models.CharField(blank=True, max_length=255)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('change_given', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('paystack_reference', models.CharField(blank=True, max_length=100)),
                ('paystack_status', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(limit_choices_to={'location_type': 'SHOP'}, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='inventory.batch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(limit_choices_to={'location_type': 'SHOP'}, on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='core.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.shift'),
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_printer_type', models.CharField(choices=[('THERMAL_80MM', '80mm Thermal Printer'), ('THERMAL_58MM', '58mm Thermal Printer'), ('A4_STANDARD', 'A4 Standard Printer'), ('NO_PRINT', 'No Printing (Digital Only)')], default='THERMAL_80MM', max_length=20)),
                ('receipt_header', models.TextField(blank=True, help_text='Custom header text for receipts')),
                ('receipt_footer', models.TextField(blank=True, help_text="Custom footer text for receipts (e.g., 'Thank you!')")),
                ('show_logo_on_receipt', models.BooleanField(default=True)),
                ('enable_cash_payment', models.BooleanField(default=True)),
                ('enable_credit_payment', models.BooleanField(default=True)),
                ('enable_ecash_payment', models.BooleanField(default=True)),
                ('paystack_public_key', models.CharField(blank=True, max_length=255)),
                ('paystack_secret_key', models.CharField(blank=True, max_length=255)),
                ('shop', models.OneToOneField(limit_choices_to={'location_type': 'SHOP'}, on_delete=django.db.models.deletion.CASCADE, related_name='shop_settings', to='core.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'Shop Settings',
            },
        ),
        migrations.AlterUniqueTogether(
            name='sale',
            unique_together={('tenant', 'sale_number')},
        ),
    ]
