# Generated by Django 5.1.4 on 2026-01-12 05:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_allow_accountant_to_shop_transfers'),
        ('customers', '0002_customer_shop'),
        ('sales', '0002_sale_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'status'], name='sales_sale_tenant__6a10bc_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'created_at'], name='sales_sale_tenant__165baa_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'shop', 'created_at'], name='sales_sale_tenant__3c0f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'payment_method'], name='sales_sale_tenant__77e463_idx'),
        ),
    ]
