# Generated by Django 5.1.4 on 2026-01-13 01:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_sales_sale_tenant__6a10bc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cost price at time of sale (from batch) for profit tracking', max_digits=12),
        ),
    ]
