# Generated by Django 5.1.4 on 2026-02-09 22:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_additional_shops'),
        ('customers', '0002_customer_shop'),
        ('sales', '0004_add_unit_cost_to_saleitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='client_sale_id',
            field=models.CharField(blank=True, help_text='Client-generated UUID for offline sale idempotency', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='has_sync_conflict',
            field=models.BooleanField(default=False, help_text='Whether this sale had stock or other conflicts during sync'),
        ),
        migrations.AddField(
            model_name='sale',
            name='offline_created_at',
            field=models.DateTimeField(blank=True, help_text='Original timestamp when sale was created offline', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sync_conflict_notes',
            field=models.TextField(blank=True, help_text='Details of any sync conflicts'),
        ),
        migrations.AddField(
            model_name='sale',
            name='synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this offline sale was synced to server', null=True),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'client_sale_id'], name='sales_sale_tenant__69d650_idx'),
        ),
    ]
