# Generated by Django 5.1.4 on 2026-02-10 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_add_offline_sync_fields'),
        ('sales', '0005_sale_client_id_sale_created_at_client_sale_device_id_and_more'),
    ]

    operations = [
    ]
