# Generated by Django 5.1.4 on 2026-03-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_merge_20260210_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsettings',
            name='receipt_printer_type',
            field=models.CharField(choices=[('THERMAL_80MM', '80mm Thermal Printer'), ('THERMAL_58MM', '58mm Thermal Printer'), ('A4_STANDARD', 'A4 Standard Printer'), ('A5_STANDARD', 'A5 Standard Printer'), ('NO_PRINT', 'No Printing (Digital Only)')], default='THERMAL_80MM', max_length=20),
        ),
    ]
