# Generated by Django 5.1.4 on 2026-04-19 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_shopsettings_receipt_printer_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_dispatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='walkin_customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sale',
            name='walkin_customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit (Customer Account)'), ('ECASH', 'E-Cash (Paystack)'), ('CHEQUE', 'Cheque'), ('MOMO', 'Mobile Money'), ('MIXED', 'Mixed Payment')], default='CASH', max_length=10),
        ),
    ]
