# Generated by Django 5.1.4 on 2026-05-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_shopsettings_receipt_printer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='enable_momo_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit (Customer Account)'), ('ECASH', 'E-Cash (Paystack)'), ('MOMO', 'Mobile Money'), ('MIXED', 'Mixed Payment')], default='CASH', max_length=10),
        ),
    ]
