# Generated by Django 5.1.4 on 2026-04-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_sale_dispatched_at_sale_dispatched_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_disputed',
            field=models.BooleanField(default=False, help_text='True if the accountant disputes the digital payment'),
        ),
    ]
