# Generated by Django 5.1.4 on 2026-05-09 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_shopsettings_enable_momo_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='accountant_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='accountant_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_accountant_confirmed',
            field=models.BooleanField(default=False, help_text='True if accountant has confirmed receipt of this digital payment'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='paystack_status',
            field=models.CharField(blank=True, help_text='Paystack transaction status', max_length=20),
        ),
    ]
