# Generated by Django 5.1.4 on 2026-05-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_sale_accountant_confirmed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='paystack_reference',
            new_name='gateway_reference',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='paystack_status',
        ),
        migrations.AddField(
            model_name='sale',
            name='gateway_status',
            field=models.CharField(blank=True, help_text='Gateway transaction status', max_length=20),
        ),
    ]
