# Generated by Django 5.1.4 on 2026-04-23 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_cashier(apps, schema_editor):
    Sale = apps.get_model('sales', 'Sale')
    # Set cashier = attendant for all existing sales
    # (Since historically the attendant was the one collecting cash if no cashier was tracked)
    for sale in Sale.objects.all():
        sale.cashier = sale.attendant
        sale.save(update_fields=['cashier'])

def reverse_backfill(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_sale_is_disputed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_cashier, reverse_backfill),
        migrations.AlterField(
            model_name='sale',
            name='attendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
