# Generated by Django 5.1.4 on 2026-05-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_sale_accountant_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Name entered manually (for walk-in or cashier workflow)', max_length=255),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Phone number entered manually', max_length=30),
        ),
    ]
