# Generated by Django 5.1.4 on 2026-05-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_sale_cashier_alter_sale_attendant'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='hide_zero_stock_items',
            field=models.BooleanField(default=False, help_text='Hide products with zero stock from the PoS product list.'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='receipt_print_copies',
            field=models.PositiveIntegerField(default=1, help_text='Number of receipt copies to print after payment in strict workflow (overrides tenant default if > 0).'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='warn_on_low_stock',
            field=models.BooleanField(default=True, help_text='Show a warning pop-up when an attendant adds more items than available stock.'),
        ),
    ]
