# Generated by Django 5.1.4 on 2026-05-20 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_sale_customer_name_sale_customer_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, help_text='The date and time the sale was dispatched.', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, help_text='The user (typically shop manager) who dispatched the goods.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_dispatched',
            field=models.BooleanField(default=False, help_text='Designates whether the goods for this sale have been dispatched by the shop manager.'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit (Customer Account)'), ('ECASH', 'E-Cash (Paystack)'), ('MOMO', 'Mobile Money'), ('MIXED', 'Mixed Payment'), ('PENDING_INVOICE', 'Pending Invoice')], default='CASH', max_length=20),
        ),
    ]
