# Generated by Django 5.1.4 on 2026-05-20 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_sale_dispatched_at_sale_dispatched_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cashier',
            field=models.ForeignKey(blank=True, help_text='The cashier who received/processed payment for this sale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_sales', to=settings.AUTH_USER_MODEL),
        ),
    ]
