# Generated by Django 5.1.4 on 2026-05-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_sale_cashier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_DISPATCH', 'Pending Dispatch'), ('COMPLETED', 'Completed'), ('VOIDED', 'Voided'), ('HELD', 'Held')], default='PENDING', max_length=20),
        ),
    ]
