# Generated by Django 5.1.4 on 2026-05-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='hide_zero_stock_in_pos',
            field=models.BooleanField(default=False, help_text='Hide products with zero stock from the POS interface.'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_DISPATCH', 'Pending Dispatch'), ('COMPLETED', 'Completed'), ('VOIDED', 'Voided'), ('REFUNDED', 'Refunded'), ('HELD', 'Held')], default='PENDING', max_length=20),
        ),
    ]
