# Generated by Django 5.1.4 on 2026-05-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_refund_always_cash_and_refund_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='auto_print_receipts',
            field=models.BooleanField(default=True, help_text='Automatically open receipt for printing after completing a sale.'),
        ),
    ]
