# Generated by Django 5.1.4 on 2026-07-10 20:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_shopsettings_auto_print_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='dispatched_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Quantity that has already been dispatched to the customer (for partial dispatch).', max_digits=12),
        ),
    ]
