# Generated by Django 5.1.7 on 2026-08-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_add_saleitem_dispatched_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='show_customer_info_on_receipt',
            field=models.BooleanField(default=True, help_text='Display customer name and phone number on printed receipts.'),
        ),
    ]
