# Generated by Django 5.1.7 on 2026-09-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_shopsettings_show_customer_info_on_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='receipt_font_family',
            field=models.CharField(choices=[('CONSOLAS', 'Consolas / Clean Monospace (Crisp on Thermal & Standard)'), ('SANSSERIF', 'Modern Sans-Serif (Arial / Segoe UI - Great for A4/A5 & Thermal)'), ('LUCIDA', 'Lucida Console / POS Monospace (Wide & Bold Monospace)'), ('ROBOTO_MONO', 'Roboto Mono / Clean Tech Monospace'), ('COURIER', 'Courier New (Traditional Monospace)'), ('MONOSPACE', 'System Default Monospace')], default='CONSOLAS', help_text='Font family used for printed receipts and waybills.', max_length=30),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='receipt_font_size',
            field=models.CharField(choices=[('COMPACT', 'Compact (Small - 90%)'), ('NORMAL', 'Standard (Normal - 100%)'), ('LARGE', 'Large (High Visibility - 110%)')], default='NORMAL', help_text='Font scale size on receipts.', max_length=20),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='receipt_font_weight',
            field=models.CharField(choices=[('NORMAL', 'Normal (400 - Recommended for A4/A5 Laser & Inkjet)'), ('MEDIUM', 'Medium / Semi-Bold (600 - Recommended for Thermal)'), ('BOLD', 'Bold / High Contrast (700 - Darkest Print)')], default='NORMAL', help_text='Font darkness/weight for receipt text.', max_length=20),
        ),
    ]
