# Generated by Django 6.0 on 2026-01-08 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_allow_accountant_to_shop_transfers'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shop',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_type': 'SHOP'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='core.location'),
        ),
    ]
