# Generated by Django 5.1.4 on 2026-05-09 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_shop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customertransaction',
            name='accountant_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='accountant_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_customer_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='is_accountant_confirmed',
            field=models.BooleanField(default=False, help_text='True if accountant has confirmed receipt of this digital payment'),
        ),
    ]
