# Generated by Django 6.0 on 2026-01-03 00:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Unit cost at time of transfer (auto-filled from batch if blank)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
