# Generated by Django 5.1.4 on 2026-02-25 01:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_additional_shops'),
        ('inventory', '0004_product_updated_by_device_product_version_inventory'),
        ('transfers', '0003_stock_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transferitem',
            name='discrepancy_notes',
            field=models.TextField(blank=True, help_text='Additional details about the discrepancy'),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='discrepancy_reason',
            field=models.CharField(blank=True, choices=[('DAMAGED', 'Damaged in Transit'), ('SHORT', 'Short Quantity'), ('EXPIRED', 'Expired'), ('REJECTED', 'Quality Rejected'), ('OTHER', 'Other')], help_text='Reason for quantity discrepancy on receipt', max_length=20),
        ),
        migrations.CreateModel(
            name='StockWriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writeoff_number', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.CharField(choices=[('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired'), ('RETURNED', 'Returned to Supplier'), ('LOST', 'Lost / Missing'), ('OTHER', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_offs', to='inventory.batch')),
                ('location', models.ForeignKey(limit_choices_to={'location_type': 'STORES'}, on_delete=django.db.models.deletion.PROTECT, related_name='write_offs', to='core.location')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_offs', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_offs', to='inventory.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'writeoff_number')},
            },
        ),
    ]
