# Generated by Django 6.0 on 2026-01-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='shop_manager_can_add_products',
            field=models.BooleanField(default=False, help_text='Allow shop managers to add new products'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='shop_manager_can_receive_stock',
            field=models.BooleanField(default=False, help_text='Allow shop managers to receive stock (create batches)'),
        ),
    ]
