# Generated by Django 6.0 on 2026-01-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tenant_shop_manager_can_add_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='allow_accountant_to_shop_transfers',
            field=models.BooleanField(default=False, help_text='Allow accountants to send cash (float/change) to shops'),
        ),
    ]
