# Generated by Django 5.1.4 on 2026-01-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_allow_accountant_to_shop_transfers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_required',
            field=models.BooleanField(default=False, help_text='If True, user must change password on next login'),
        ),
    ]
