# Generated by Django 5.1.4 on 2026-01-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_password_reset_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='receipt_copies',
            field=models.PositiveIntegerField(default=1, help_text='Number of receipt copies to print per sale (for shops)'),
        ),
    ]
