# Generated by Django 5.1.4 on 2026-01-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_location_receipt_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for superuser (not visible to tenant)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='auto_renew',
            field=models.BooleanField(default=False, help_text="If True, subscription won't auto-expire"),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_end_date',
            field=models.DateField(blank=True, help_text='When subscription expires', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_start_date',
            field=models.DateField(blank=True, help_text='When subscription started', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended')], default='TRIAL', help_text='Current subscription status', max_length=20),
        ),
    ]
