# Generated by Django 5.1.4 on 2026-01-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='last_notification_sent',
            field=models.DateField(blank=True, help_text='Date of last subscription notification', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='When account was locked due to extended inactivity', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='onboarding_paid',
            field=models.BooleanField(default=False, help_text='Whether onboarding fee has been paid'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='setup_completed_at',
            field=models.DateTimeField(blank=True, help_text='When tenant completed initial setup', null=True),
        ),
    ]
