# Generated by Django 5.1.4 on 2026-01-21 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tenant_last_notification_sent_tenant_locked_at_and_more'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, help_text='Current subscription plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='subscriptions.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('TENANT_MANAGER', 'Tenant Manager'), ('ADMIN', 'Admin'), ('PRODUCTION_MANAGER', 'Production Manager'), ('STORES_MANAGER', 'Stores Manager'), ('SHOP_MANAGER', 'Shop Manager'), ('SHOP_ATTENDANT', 'Shop Attendant'), ('ACCOUNTANT', 'Accountant'), ('AUDITOR', 'Auditor')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive'), ('LOCKED', 'Locked')], default='TRIAL', help_text='Current subscription status', max_length=20),
        ),
    ]
