# Generated by Django 5.1.4 on 2026-01-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tenant_subscription_plan_alter_role_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='additional_shops',
            field=models.PositiveIntegerField(default=0, help_text='Additional shops beyond plan limit (for Premium)'),
        ),
    ]
