# Generated by Django 5.1.4 on 2026-03-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_additional_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='shops_can_see_other_stock',
            field=models.BooleanField(default=True, help_text='Allow shops to see stock levels at other locations, batches, and the full stock breakdown'),
        ),
    ]
