# Generated by Django 5.1.4 on 2026-04-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tenant_shops_can_see_other_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='require_accountant_for_bulk_receiving',
            field=models.BooleanField(default=False, help_text='If enabled, bulk Goods Receipts must be approved by an accountant before converting to batches'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='require_customer_on_invoice',
            field=models.BooleanField(default=False, help_text='Require a customer profile (with a valid phone number) when creating sales/invoices'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='use_bulk_inventory_receiving',
            field=models.BooleanField(default=False, help_text='Enable bulk Goods Receipt receiving instead of one-by-one receiving'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='use_strict_sales_workflow',
            field=models.BooleanField(default=False, help_text='Enforce Attendant(Invoice) -> Cashier(Pay) -> Manager(Dispatch) workflow'),
        ),
    ]
