# Generated by Django 5.1.4 on 2026-05-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tenant_shops_can_see_other_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='allow_momo_payments',
            field=models.BooleanField(default=False, help_text='Allow shops to receive Mobile Money payments'),
        ),
    ]
