# Generated by Django 5.1.4 on 2026-04-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tenant_require_accountant_for_bulk_receiving_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='allow_shop_to_shop_transfers',
            field=models.BooleanField(default=False, help_text='Allow shops to transfer stock directly to other shops'),
        ),
    ]
