# Generated by Django 5.1.4 on 2026-05-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tenant_allow_momo_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='shop_manager_can_delete_categories',
            field=models.BooleanField(default=False, help_text='Allow shop managers to delete product categories'),
        ),
    ]
