# Generated by Django 5.1.4 on 2026-05-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tenant_shop_manager_can_delete_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='cashier_transfers_to_bank',
            field=models.BooleanField(default=False, help_text='In cashier workflow, transfers go to bank (not accountant)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='use_cashier_workflow',
            field=models.BooleanField(default=False, help_text='Enable dedicated Cashier role (Attendant creates invoice, Cashier collects payment)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='use_strict_sales_workflow',
            field=models.BooleanField(default=False, help_text='Enforce strict Attendant → Cashier → Manager dispatch workflow'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='waive_shift_requirement',
            field=models.BooleanField(default=False, help_text='Allow sales without opening a shift first'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('TENANT_MANAGER', 'Tenant Manager'), ('ADMIN', 'Admin'), ('PRODUCTION_MANAGER', 'Production Manager'), ('STORES_MANAGER', 'Stores Manager'), ('SHOP_MANAGER', 'Shop Manager'), ('SHOP_CASHIER', 'Shop Cashier'), ('SHOP_ATTENDANT', 'Shop Attendant'), ('ACCOUNTANT', 'Accountant'), ('AUDITOR', 'Auditor')], max_length=50, unique=True),
        ),
    ]
