# Generated by Django 5.1.4 on 2026-04-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tenant_allow_shop_to_shop_transfers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='allow_shop_to_accountant_transfers',
            field=models.BooleanField(default=True, help_text='Allow shops to transfer cash deposits to the accountant'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='allow_shop_to_bank_transfers',
            field=models.BooleanField(default=True, help_text='Allow shops to transfer cash deposits directly to a bank'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('TENANT_MANAGER', 'Tenant Manager'), ('ADMIN', 'Admin'), ('PRODUCTION_MANAGER', 'Production Manager'), ('STORES_MANAGER', 'Stores Manager'), ('SHOP_MANAGER', 'Shop Manager'), ('SHOP_CASHIER', 'Shop Cashier'), ('SHOP_ATTENDANT', 'Shop Attendant'), ('ACCOUNTANT', 'Accountant'), ('AUDITOR', 'Auditor')], max_length=50, unique=True),
        ),
    ]
