# Generated by Django 5.1.4 on 2026-05-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_tenant_cashier_transfers_to_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='enable_refunds',
            field=models.BooleanField(default=False, help_text='Allow processed sales to be formally refunded'),
        ),
    ]
