# Generated by Django 5.1.4 on 2026-04-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_tenant_allow_shop_to_accountant_transfers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='receipt_print_copies',
            field=models.PositiveIntegerField(default=3, help_text='Number of receipt copies to print upon successful payment.'),
        ),
    ]
