# Generated by Django 5.1.4 on 2026-05-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tenant_enable_refunds'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='accountants_can_approve_adjustments',
            field=models.BooleanField(default=False, help_text='Allow accountants to approve stock adjustments in addition to auditors/admins'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='use_strict_sales_workflow',
            field=models.BooleanField(default=False, help_text='Enforce strict Attendant -> Cashier -> Manager dispatch workflow'),
        ),
    ]
