# Generated by Django 5.1.4 on 2026-05-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tenant_receipt_print_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='stock_adjustment_approver',
            field=models.CharField(choices=[('MANAGER', 'Shop Manager / Admin Only'), ('AUDITOR', 'Auditor Only'), ('BOTH', 'Both Manager and Auditor')], default='MANAGER', help_text='Who must approve pending stock adjustments.', max_length=10),
        ),
    ]
