# Generated by Django 5.1.4 on 2026-05-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_shopsettings_new_fields_and_auditor_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='include_opening_cash_in_transfer',
            field=models.BooleanField(default=True, help_text="Include the shift opening cash (float) in the manager's/cashier's transferable cash-on-hand balance"),
        ),
        migrations.AddField(
            model_name='tenant',
            name='shop_manager_can_delete_products',
            field=models.BooleanField(default=False, help_text='Allow shop managers to delete products and categories from the main inventory'),
        ),
    ]
