# Generated by Django 5.1.4 on 2026-05-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_tenant_accountants_can_approve_adjustments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='pricing_control_mode',
            field=models.CharField(choices=[('SHOP_MANAGER', 'Shop Managers Set Prices (Per Shop)'), ('ACCOUNTANT_PER_SHOP', 'Accountant Sets Prices (Per Shop)'), ('ACCOUNTANT_UNIFORM', 'Accountant Sets Uniform Prices (All Shops)')], default='SHOP_MANAGER', help_text='Determine who controls product pricing and how.', max_length=50),
        ),
    ]
