# Generated by Django 5.1.4 on 2026-05-22 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_scheduledemail_featureintrohistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureintrohistory',
            name='feedback_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featureintrohistory',
            name='feedback_helpful',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FeatureMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(help_text="A unique identifier (e.g. 'transfer_discrepancy')", max_length=100, unique=True)),
                ('title', models.CharField(help_text='Email Subject Line', max_length=255)),
                ('content', models.TextField(help_text='HTML content of the email')),
                ('is_active', models.BooleanField(default=True, help_text='If active, it is eligible to be randomly sent to tenants')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feature_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='featureintrohistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='featureintrohistory',
            name='feature_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.featuremessage'),
        ),
        migrations.AlterUniqueTogether(
            name='featureintrohistory',
            unique_together={('tenant', 'feature_message')},
        ),
        migrations.RemoveField(
            model_name='featureintrohistory',
            name='feature_key',
        ),
    ]
