# Generated by Django 5.1.4 on 2026-05-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_featureintrohistory_feedback_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='refund_always_cash',
            field=models.BooleanField(default=True, help_text="When enabled, all refunds are paid back in physical cash from the shop's cash-on-hand, regardless of the original payment method (e-cash, momo, etc.). When disabled, refunds are processed by the same medium as the original payment."),
        ),
    ]
