# Generated by Django 5.1.4 on 2026-05-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_refund_always_cash_and_refund_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='allow_inter_shop_transfers',
            field=models.BooleanField(default=False, help_text='Allow shops to request and transfer stock between each other'),
        ),
    ]
