# Generated by Django 5.1.4 on 2026-07-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_tenant_allow_inter_shop_transfers'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='allow_partial_dispatch',
            field=models.BooleanField(default=True, help_text='Allow partial dispatch in this shop'),
        ),
    ]
