# Generated by Django 5.1.4 on 2026-05-09 18:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('core', '0012_tenant_allow_momo_payments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fund_source', models.CharField(choices=[('CASH', 'Physical Cash'), ('ECASH', 'E-Cash'), ('MOMO', 'Local Momo')], max_length=10)),
                ('teller_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional information about the deposit')),
                ('receipt_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accountant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_transfers', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Bank Transfer',
                'verbose_name_plural': 'Bank Transfers',
                'ordering': ['-created_at'],
            },
        ),
    ]
