# Generated by Django 5.1.4 on 2026-04-21 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_migrate_expenditures'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expenditure',
        ),
    ]
