# Generated by Django 5.1.4 on 2026-04-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_delete_expenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransfer',
            name='source_type',
            field=models.CharField(choices=[('CASH', 'Physical Cash'), ('ECASH', 'E-Cash Wallet'), ('MOMO', 'Mobile Money Wallet')], default='CASH', max_length=10),
        ),
    ]
