# Generated by Django 5.1.4 on 2026-04-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_cashtransfer_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditureitem',
            name='source_of_funds',
            field=models.CharField(blank=True, choices=[('ACCOUNTANT', 'From Accountant'), ('SHOP_CASH', "From Shop's Cash-on-Hand")], max_length=20, null=True),
        ),
    ]
