# Generated by Django 5.1.4 on 2026-05-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_expenditureitem_source_of_funds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransfer',
            name='transfer_type',
            field=models.CharField(choices=[('DEPOSIT', 'Cash Deposit'), ('FLOAT', 'Float/Change'), ('EXPENDITURE', 'Expenditure')], max_length=15),
        ),
    ]
