# Generated by Django 5.1.4 on 2026-05-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_expenditure_transfer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransfer',
            name='destination',
            field=models.CharField(choices=[('ACCOUNTANT', 'Accountant'), ('BANK', 'Bank')], default='BANK', help_text='Where the cash is being transferred to', max_length=20),
        ),
    ]
