# Generated by Django 5.1.4 on 2026-05-21 12:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_cashtransfer_destination'),
        ('core', '0014_tenant_cashier_transfers_to_bank_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalFundWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fund_source', models.CharField(choices=[('ECASH', 'E-Cash'), ('MOMO', 'Local Momo')], max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Optional reference notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accountant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='digital_withdrawals_performed', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='digital_withdrawals', to='core.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Digital Fund Withdrawal',
                'verbose_name_plural': 'Digital Fund Withdrawals',
                'ordering': ['-created_at'],
            },
        ),
    ]
