# Generated by Django 5.1.4 on 2026-05-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_digitalfundwithdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalfundwithdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Positive = withdrawal (deducts from shop balance). Negative = refund reversal (restores shop balance).', max_digits=12),
        ),
    ]
