# Generated by Django 5.1.4 on 2026-05-26 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_digital_fund_allow_negative_for_refunds'),
        ('payments', '0003_paymentproviderconfig_ecashledger_provider_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalfundwithdrawal',
            name='provider_config',
            field=models.ForeignKey(blank=True, help_text='The E-Cash platform this withdrawal was pulled from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_withdrawals', to='payments.paymentproviderconfig'),
        ),
    ]
