# Generated by Django 5.1.4 on 2026-05-26 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_digitalfundwithdrawal_provider_config'),
        ('payments', '0003_paymentproviderconfig_ecashledger_provider_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransfer',
            name='provider_config',
            field=models.ForeignKey(blank=True, help_text='The E-Cash platform this bank transfer is drawn from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transfers', to='payments.paymentproviderconfig'),
        ),
    ]
