# Generated by Django 5.1.4 on 2026-01-21 06:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_tenant_last_notification_sent_tenant_locked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(choices=[('STARTER', 'Starter'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Monthly base price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_shops', models.PositiveIntegerField(default=2, help_text='Maximum number of shop locations included')),
                ('additional_shop_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price per additional shop beyond max_shops (for Premium)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature descriptions')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['display_order', 'base_price'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('EXPIRY_WARNING', 'Expiry Warning'), ('EXPIRED', 'Subscription Expired'), ('DEACTIVATION_WARNING', 'Deactivation Warning'), ('DEACTIVATED', 'Account Deactivated'), ('LOCKED', 'Account Locked')], max_length=30)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('IN_APP', 'In-App')], max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('message_preview', models.TextField(blank=True, help_text='Preview/summary of the message sent')),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_notifications', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Subscription Notification Log',
                'verbose_name_plural': 'Subscription Notification Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, help_text='Unique receipt number', max_length=50, unique=True)),
                ('payment_type', models.CharField(choices=[('ONBOARDING', 'Onboarding Fee'), ('SUBSCRIPTION', 'Subscription'), ('RENEWAL', 'Renewal'), ('ADDITIONAL', 'Additional Payment')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOMO', 'Mobile Money'), ('PAYSTACK', 'Paystack'), ('MANUAL', 'Manual Entry')], default='MANUAL', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('paystack_reference', models.CharField(blank=True, max_length=100)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('plan_name', models.CharField(blank=True, max_length=50)),
                ('plan_details', models.JSONField(blank=True, default=dict, help_text='Snapshot of plan details at payment time')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payments_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Subscription Payment',
                'verbose_name_plural': 'Subscription Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantPricingOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarding_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Custom onboarding fee (leave blank for default)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, help_text='Custom monthly subscription price (leave blank for plan default)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('additional_shop_price', models.DecimalField(blank=True, decimal_places=2, help_text='Custom additional shop price (leave blank for plan default)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage applied to subscription', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this pricing arrangement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_overrides_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_override', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Pricing Override',
                'verbose_name_plural': 'Tenant Pricing Overrides',
            },
        ),
        migrations.CreateModel(
            name='TenantManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary manager receives all notifications')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(limit_choices_to={'role__name': 'TENANT_MANAGER'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_tenants', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_managers', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Manager Assignment',
                'verbose_name_plural': 'Tenant Manager Assignments',
                'unique_together': {('manager', 'tenant')},
            },
        ),
    ]
