# Generated by Django 5.1.4 on 2026-01-21 16:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_create_default_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='annual_additional_shop_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Additional shop price when paying annually (discounted)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='annual_base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly price when paying annually (discounted)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
