# Generated by Django 5.1.4 on 2026-02-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_set_annual_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='shops_paid',
            field=models.PositiveIntegerField(default=0, help_text='Number of shops paid for (Premium plans)'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='payment_type',
            field=models.CharField(choices=[('ONBOARDING', 'Onboarding Fee'), ('SUBSCRIPTION', 'Subscription'), ('RENEWAL', 'Renewal'), ('SHOP_TOPUP', 'Shop Top-up'), ('ADDITIONAL', 'Additional Payment')], max_length=20),
        ),
    ]
