# Generated by Django 5.1.4 on 2026-04-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_add_lite_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='code',
            field=models.CharField(choices=[('LITE', 'Lite'), ('STARTER', 'Starter'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], max_length=20, unique=True),
        ),
    ]
