# Generated by Django 6.0 on 2026-01-11 02:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_tenant_allow_accountant_to_shop_transfers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ECashLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PAYMENT', 'E-Cash Payment Received'), ('WITHDRAWAL', 'E-Cash Withdrawn to Cash'), ('REFUND', 'E-Cash Refund'), ('ADJUSTMENT', 'Manual Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for incoming, negative for outgoing', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('reference_type', models.CharField(blank=True, help_text='Type of source: Sale, Withdrawal, Refund', max_length=50)),
                ('reference_id', models.IntegerField(blank=True, help_text='ID of the source record', null=True)),
                ('paystack_reference', models.CharField(blank=True, help_text='Paystack transaction reference', max_length=100)),
                ('provider', models.CharField(default='PAYSTACK', help_text='Payment provider used', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecash_transactions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'E-Cash Ledger Entry',
                'verbose_name_plural': 'E-Cash Ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ECashWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('withdrawal_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('withdrawn_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecash_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'E-Cash Withdrawal',
                'verbose_name_plural': 'E-Cash Withdrawals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('PAYSTACK', 'Paystack'), ('FLUTTERWAVE', 'Flutterwave'), ('MTN_MOMO', 'MTN Mobile Money'), ('VODAFONE_CASH', 'Vodafone Cash')], default='PAYSTACK', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Enable this payment provider')),
                ('public_key', models.CharField(blank=True, help_text='Public/Test key for frontend', max_length=512)),
                ('_secret_key', models.CharField(blank=True, db_column='secret_key', help_text='Secret key (encrypted)', max_length=512)),
                ('_webhook_secret', models.CharField(blank=True, db_column='webhook_secret', help_text='Webhook secret for verifying callbacks (encrypted)', max_length=512)),
                ('callback_url', models.URLField(blank=True, help_text='Auto-generated webhook URL for this tenant')),
                ('test_mode', models.BooleanField(default=True, help_text='Use test/sandbox credentials')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Payment Provider Settings',
                'verbose_name_plural': 'Payment Provider Settings',
                'unique_together': {('tenant', 'provider')},
            },
        ),
    ]
