# Generated by Django 5.1.4 on 2026-05-26 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_tenant_allow_inter_shop_transfers'),
        ('payments', '0002_add_shop_to_ecash'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('PAYSTACK', 'Paystack'), ('NALOPAY', 'Nalopay'), ('APPSNMOBILE', 'AppsnMobile (Orchard)'), ('EXPRESSPAY', 'ExpressPay')], default='PAYSTACK', max_length=20)),
                ('nickname', models.CharField(default='Default', help_text="Friendly name, e.g. 'Main Paystack' or 'Backup ExpressPay'", max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Enable this payment provider config')),
                ('public_key', models.CharField(blank=True, help_text='Public/Test key for frontend', max_length=512)),
                ('_secret_key', models.CharField(blank=True, db_column='secret_key', help_text='Secret key (encrypted)', max_length=512)),
                ('_webhook_secret', models.CharField(blank=True, db_column='webhook_secret', help_text='Webhook secret for verifying callbacks (encrypted)', max_length=512)),
                ('merchant_id', models.CharField(blank=True, help_text='For ExpressPay/AppsnMobile', max_length=256)),
                ('callback_url', models.URLField(blank=True, help_text='Webhook URL for this provider config')),
                ('test_mode', models.BooleanField(default=True, help_text='Use test/sandbox credentials')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Payment Provider Config',
                'verbose_name_plural': 'Payment Provider Configs',
                'unique_together': {('tenant', 'nickname')},
            },
        ),
        migrations.AddField(
            model_name='ecashledger',
            name='provider_config',
            field=models.ForeignKey(blank=True, help_text='Which provider config was used for this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentproviderconfig'),
        ),
        migrations.CreateModel(
            name='ShopPaymentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, help_text='The default provider for this shop')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Lower = higher priority for fallback')),
                ('provider_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_assignments', to='payments.paymentproviderconfig')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_assignments', to='core.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['priority'],
                'unique_together': {('shop', 'provider_config')},
            },
        ),
        migrations.DeleteModel(
            name='PaymentProviderSettings',
        ),
    ]
