# Generated by Django 5.1.4 on 2026-05-11 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tenant_shop_manager_can_delete_categories'),
        ('payments', '0002_add_shop_to_ecash'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentprovidersettings',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ecashledger',
            name='paystack_reference',
        ),
        migrations.AddField(
            model_name='ecashledger',
            name='gateway_reference',
            field=models.CharField(blank=True, help_text='Gateway transaction reference', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentprovidersettings',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Leave blank to apply to all shops', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to='core.location'),
        ),
        migrations.AlterField(
            model_name='paymentprovidersettings',
            name='provider',
            field=models.CharField(choices=[('PAYSTACK', 'Paystack'), ('FLUTTERWAVE', 'Flutterwave'), ('APPSNMOBILE', 'AppsNMobile'), ('HUBTEL', 'Hubtel')], default='PAYSTACK', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='paymentprovidersettings',
            unique_together={('tenant', 'provider', 'shop')},
        ),
    ]
