# Generated by Django 5.1.4 on 2026-04-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_shop_to_ecash'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecashledger',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed')], default='CONFIRMED', help_text='Accountant confirmation status', max_length=15),
        ),
        migrations.AddField(
            model_name='ecashledger',
            name='wallet_type',
            field=models.CharField(choices=[('ECASH', 'E-Cash / Paystack'), ('MOMO', 'Mobile Money')], default='ECASH', max_length=10),
        ),
    ]
