# Generated by Django 5.1.4 on 2026-04-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_ecashledger_status_ecashledger_wallet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecashledger',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('DISPUTED', 'Disputed')], default='CONFIRMED', help_text='Accountant confirmation status', max_length=15),
        ),
    ]
