# Generated by Django 5.1.4 on 2026-05-27 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentproviderconfig_ecashledger_provider_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecashwithdrawal',
            name='provider_config',
            field=models.ForeignKey(blank=True, help_text='Specific platform to withdraw from (leave blank for all platforms)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecash_withdrawals', to='payments.paymentproviderconfig'),
        ),
    ]
