# Generated by Django 5.1.4 on 2026-05-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentprovidersettings_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentprovidersettings',
            options={'ordering': ['tenant', 'shop', 'priority', 'provider'], 'verbose_name': 'Payment Provider Settings', 'verbose_name_plural': 'Payment Provider Settings'},
        ),
        migrations.AddField(
            model_name='paymentprovidersettings',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Priority order (0=highest)'),
        ),
    ]
