# Generated by Django 5.1.4 on 2026-05-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_paymentprovidersettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprovidersettings',
            name='base_url',
            field=models.URLField(blank=True, help_text='Custom base URL for the API (if required by provider)'),
        ),
        migrations.AlterField(
            model_name='paymentprovidersettings',
            name='provider',
            field=models.CharField(choices=[('PAYSTACK', 'Paystack'), ('FLUTTERWAVE', 'Flutterwave'), ('APPSNMOBILE', 'AppsNMobile'), ('HUBTEL', 'Hubtel'), ('NALO', 'Nalo')], default='PAYSTACK', max_length=20),
        ),
    ]
