# Generated by Django 5.1.4 on 2026-07-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_ecashwithdrawal_provider_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecashledger',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Raw response data from the payment provider', null=True),
        ),
    ]
