# Generated by Django 6.0 on 2026-01-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryledger',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUST', 'Adjustment'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('DAMAGE', 'Damage/Write-off'), ('PRODUCTION', 'Production'), ('DISPUTE_REVERSAL', 'Dispute Reversal')], max_length=20),
        ),
    ]
