# Generated by Django 5.1.4 on 2026-01-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_allow_accountant_to_shop_transfers'),
        ('inventory', '0002_stock_request'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'is_active'], name='inventory_p_tenant__2cb5ab_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'sku'], name='inventory_p_tenant__208840_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'category'], name='inventory_p_tenant__c2c69b_idx'),
        ),
    ]
