# Generated by Django 5.1.4 on 2026-01-29 23:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_additional_shops'),
        ('inventory', '0003_product_inventory_p_tenant__2cb5ab_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_by_device',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('version', models.IntegerField(default=1)),
                ('updated_by_device', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='core.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='inventory.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'Inventory Snapshots',
                'indexes': [models.Index(fields=['tenant', 'product', 'location'], name='inventory_i_tenant__77a287_idx'), models.Index(fields=['tenant', 'updated_at'], name='inventory_i_tenant__4715c1_idx')],
                'unique_together': {('tenant', 'product', 'location')},
            },
        ),
    ]
