# Generated by Django 5.1.4 on 2026-01-29 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_add_additional_shops'),
        ('sales', '0005_sale_client_id_sale_created_at_client_sale_device_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=50)),
                ('sync_direction', models.CharField(choices=[('device_to_server', 'Device to Server'), ('server_to_device', 'Server to Device')], max_length=20)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('conflict', 'Conflict')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('sale_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='sales.sale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'device_id'], name='sync_synclo_tenant__76a7d4_idx'), models.Index(fields=['tenant', 'created_at'], name='sync_synclo_tenant__a739b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('server_id', models.CharField(blank=True, max_length=100, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('device_id', models.CharField(max_length=100)),
                ('shop', models.ForeignKey(limit_choices_to={'location_type': 'SHOP'}, on_delete=django.db.models.deletion.CASCADE, related_name='sync_queue', to='core.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['tenant', 'synced'], name='sync_syncqu_tenant__7167a5_idx'), models.Index(fields=['tenant', 'shop', 'synced'], name='sync_syncqu_tenant__1c1b41_idx')],
            },
        ),
    ]
