# Generated by Django 5.1.4 on 2026-03-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='device_info',
            field=models.CharField(blank=True, help_text='User Agent / Device Info', max_length=255, null=True),
        ),
    ]
