"""
Shared PDF export utilities.
Provides helpers for creating styled PDF documents from tabular data.
"""
import io
from django.http import HttpResponse
from django.utils import timezone
from reportlab.lib import colors
from reportlab.lib.pagesizes import landscape, A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch

def export_to_pdf(filename, title, headers, rows, additional_tables=None, metadata=None):
    """
    Export data to a PDF response.
    
    Args:
        filename: Download filename (should end with .pdf)
        title: Main document title
        headers: List of column header strings
        rows: List of lists/tuples, one per data row
        additional_tables: List of tuples (title, headers, rows) for extra sheets
        metadata: Dict containing 'generator_name', 'shop_name', 'date_range'
    """
    buffer = io.BytesIO()
    
    # Use landscape A4 for wider tables
    doc = SimpleDocTemplate(
        buffer, 
        pagesize=landscape(A4),
        rightMargin=0.5*inch, leftMargin=0.5*inch,
        topMargin=0.5*inch, bottomMargin=0.5*inch
    )
    
    elements = []
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'MainTitle',
        parent=styles['Heading1'],
        fontSize=16,
        spaceAfter=6,
        textColor=colors.HexColor('#2C3E50')
    )
    meta_style = ParagraphStyle(
        'MetaText',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#555555'),
        spaceAfter=4
    )
    
    # Title
    if metadata and metadata.get('shop_name'):
        title = f"{title} - {metadata.get('shop_name')}"
        
    elements.append(Paragraph(title, title_style))
    
    # Metadata headers
    if metadata:
        if metadata.get('date_range'):
            elements.append(Paragraph(f"<b>Date Range:</b> {metadata.get('date_range')}", meta_style))
            
        generator = metadata.get('generator_name', 'System')
        gen_time = timezone.now().strftime('%Y-%m-%d %H:%M:%S')
        elements.append(Paragraph(f"<b>Generated By:</b> {generator} on {gen_time}", meta_style))
    else:
        gen_time = timezone.now().strftime('%Y-%m-%d %H:%M:%S')
        elements.append(Paragraph(f"<b>Generated on:</b> {gen_time}", meta_style))
        
    elements.append(Spacer(1, 16))
    
    # Main Table
    _add_table_to_elements(elements, headers, rows)
    
    # Additional Tables (for multi-sheet equivalent)
    if additional_tables:
        for t_title, t_headers, t_rows in additional_tables:
            elements.append(Spacer(1, 24))
            elements.append(Paragraph(t_title, styles['Heading2']))
            elements.append(Spacer(1, 12))
            _add_table_to_elements(elements, t_headers, t_rows)
            
    doc.build(elements)
    
    if not filename.endswith('.pdf'):
        filename += '.pdf'
        
    response = HttpResponse(buffer.getvalue(), content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="{filename}"'
    return response

def _add_table_to_elements(elements, headers, rows):
    """Format and add a table to the PDF elements list."""
    # Convert data to string to avoid reportlab type errors
    data = [headers]
    for row in rows:
        data.append([str(item) if item is not None else "" for item in row])
        
    # Create Table. We let reportlab auto-size columns, but restrict total width
    # by using '*' for column widths if possible, though default works well for most.
    t = Table(data, repeatRows=1)
    t.setStyle(TableStyle([
        # Header style
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2C3E50')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
        ('TOPPADDING', (0, 0), (-1, 0), 8),
        
        # Body style
        ('ALIGN', (0, 1), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 9),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 6),
        ('TOPPADDING', (0, 1), (-1, -1), 6),
        
        # Grid lines
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#D5D8DC')),
    ]))
    
    # Alternate row colors
    for i in range(1, len(data)):
        if i % 2 == 0:
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, i), (-1, i), colors.HexColor('#F8F9FA'))
            ]))
            
    elements.append(t)
