# Generated by Django 5.1.4 on 2026-01-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TRANSFER_SENT', 'Transfer Sent'), ('TRANSFER_RECEIVED', 'Transfer Received'), ('TRANSFER_DISPUTED', 'Transfer Disputed'), ('LOW_STOCK', 'Low Stock Alert'), ('EXPIRY_WARNING', 'Expiry Warning'), ('SUBSCRIPTION_EXPIRY', 'Subscription Expiry'), ('SUBSCRIPTION_DEACTIVATED', 'Subscription Deactivated'), ('ACCOUNT_LOCKED', 'Account Locked'), ('SYSTEM', 'System Notification')], default='SYSTEM', max_length=30),
        ),
    ]
