# Generated by Django 5.1.4 on 2026-05-25 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_tenant_allow_inter_shop_transfers'),
        ('notifications', '0004_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('post_type', models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('PRICE_ALERT', 'Price Alert'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('target_role', models.CharField(choices=[('ALL', 'All Users'), ('SHOP_MANAGER', 'Shop Managers'), ('SHOP_ATTENDANT', 'Shop Attendants'), ('ACCOUNTANT', 'Accountants'), ('AUDITOR', 'Auditors'), ('STORES_MANAGER', 'Stores Managers'), ('ADMIN', 'Admins')], default='ALL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletin_posts', to=settings.AUTH_USER_MODEL)),
                ('target_location', models.ForeignKey(blank=True, help_text='If set, only users at this location will see the post (unless target_role is more specific)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_posts', to='core.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulletinRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('bulletin_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='notifications.bulletinpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('bulletin_post', 'user')},
            },
        ),
    ]
