# Generated by Django 5.1.4 on 2026-05-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_tenant_allow_inter_shop_transfers'),
        ('notifications', '0005_bulletinpost_bulletinread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletinpost',
            name='target_location',
        ),
        migrations.RemoveField(
            model_name='bulletinpost',
            name='target_role',
        ),
        migrations.AddField(
            model_name='bulletinpost',
            name='target_locations',
            field=models.ManyToManyField(blank=True, help_text='If none selected, defaults to all locations.', related_name='targeted_bulletins', to='core.location'),
        ),
        migrations.AddField(
            model_name='bulletinpost',
            name='target_roles',
            field=models.ManyToManyField(blank=True, help_text='If none selected, defaults to all roles.', related_name='targeted_bulletins', to='core.role'),
        ),
    ]
