# Generated by Django 5.1.4 on 2026-05-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_remove_bulletinpost_target_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpost',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text="If true, this post is pinned to the top of the user's history."),
        ),
    ]
