# Generated by Django 5.1.4 on 2026-05-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_bulletinpost_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinpost',
            name='post_type',
            field=models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('PRICE_ALERT', 'Price Alert'), ('SYSTEM_UPDATE', 'Feature/System Update'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TRANSFER_SENT', 'Transfer Sent'), ('TRANSFER_RECEIVED', 'Transfer Received'), ('TRANSFER_DISPUTED', 'Transfer Disputed'), ('STOCK_ADJUSTMENT', 'Stock Adjustment'), ('LOW_STOCK', 'Low Stock Alert'), ('EXPIRY_WARNING', 'Expiry Warning'), ('SUBSCRIPTION_EXPIRY', 'Subscription Expiry'), ('SUBSCRIPTION_DEACTIVATED', 'Subscription Deactivated'), ('ACCOUNT_LOCKED', 'Account Locked'), ('PRICE_CHANGE', 'Price Change Alert'), ('INVOICE_PAID', 'Invoice Paid'), ('SYSTEM', 'System Notification')], default='SYSTEM', max_length=30),
        ),
    ]
